name: Build and release
on:
  workflow_dispatch:
    inputs:
      name_append:
        type: string
        description: Extra text (appended to release name)
        required: false
      body:
        type: string
        description: Release body text
        required: false
      is_prerelease:
        type: boolean
        description: Mark as prerelease
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3

      - name: Clean Node.js package install
        run: |
          npm ci

      - name: Build for Firefox
        run: |
          npm run build-firefox

      - name: Zip Firefox build output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r firefox.zip . -i ./dist/firefox/*

      - name: Build for Chromium
        run: |
          npm run build-chromium

      - name: Zip Chromium build output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r chromium.zip . -i ./dist/chromium/*

      - name: Get project version
        id: version-getter
        run: |
          version=$(./utils/get_version.sh)
          echo "::set-output name=version::$version"

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ inputs.is_prerelease }}
          name: v${{ steps.version-getter.outputs.version }}${{ inputs.name_append }}
          tag_name: v${{ steps.version-getter.outputs.version }}
          body: ${{ inputs.body }}
          files: |
            ./firefox.zip
            ./chromium.zip
